name:                wai-middleware-buffered-logging
version:             0.1.0.0
github:              ChrisCoffey/wai-middleware-buffered-logging
license:             BSD3
author:              Chris Coffey
maintainer:          chris@collegevine.com
copyright:           2017 Chris Coffey

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/wai-middleware-buffered-logging#readme>

dependencies:
- base >= 4.7 && < 5
- wai
- containers
- bytestring
- time

library:
  source-dirs: src
  exposed-modules:
  - Network.Wai.Logging.Buffered

executables:
  example:
    main:                Main.hs
    source-dirs:         example
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wai-middleware-buffered-logging
    - wai
    - warp
    - http-types
    - containers
    - bytestring
    - time

tests:
  wai-middleware-buffered-logging-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wai-middleware-buffered-logging
